[package]
name = "year_2018"
version = "0.1.0"
authors = ["Valatos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../aoc" }